Repository pixijs/pixi-react, pull requests merged in 2025-02, with the labels that each got.

#568 fix: update `useTick` `isEnabled` typedef and readme
  README.md
  src/typedefs/UseTickOptions.ts
Labels: bug, v8, ready to merge

#572 Remove asset hooks
  README.md
  src/constants/UseAssetsStatus.ts
  src/hooks/useAsset.ts
  src/hooks/useAssets.ts
  src/hooks/useSuspenseAssets.ts
  src/index.ts
  src/typedefs/UseAssetsOptions.ts
  src/typedefs/UseAssetsResult.ts
  test/unit/hooks/useAssets.test.tsx
  test/unit/index.test.ts
Labels: v8, ready to merge

#574 Add 'writable' descriptor check to isReadOnlyProperty
  src/helpers/isReadOnlyProperty.ts
Labels: bug, v8

#577 Bundle @pixi/react for use without bundler
  package-lock.json
  package.json
  rollup.config.mjs
Labels: enhancement, v8

#578 docs: initial docs site for v8
  docs/docs/about.jsx
  docs/docs/about.mdx
  docs/docs/components/_category_.json
  docs/docs/components/application.mdx
  docs/docs/components/custom-components.mdx
  docs/docs/components/pixi-components.mdx
  docs/docs/extend.mdx
  docs/docs/getting-started.mdx
  docs/docs/hooks/_category_.json
  docs/docs/hooks/useApplication.mdx
  docs/docs/hooks/useExtend.mdx
  docs/docs/hooks/useTick.mdx
  docs/docs/typescript.mdx
  docs/docusaurus.config.ts
  docs/package.json
  docs/sidebars.ts
  docs/src/components/Editor/Editor.tsx
  docs/src/components/Editor/EmbeddedEditor.tsx
  docs/src/examples/basic/App.jsx
  docs/src/examples/basic/BunnySprite.jsx
  docs/src/pages/index.tsx
  package-lock.json
Labels: v8
